sspring.jackson.default-property-inclusion: NON_NULL
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG

naver:
  clientId: mv9agrezdc
  clientSecret: UyLTTU63LAddxCB3LPUJqAaAv60xrLJBw7vvYXJb